"""created_by added to task entity

Revision ID: 0c480e25b34e
Revises: d113c1a4cb6f
Create Date: 2026-09-19 16:22:46.638877

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c480e25b34e'
down_revision: Union[str, Sequence[str], None] = 'd113c1a4cb6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by', sa.Integer(), nullable=False), schema='tasks')
    op.create_foreign_key(None, 'task', 'user', ['created_by'], ['id'], source_schema='tasks', referent_schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', schema='tasks', type_='foreignkey')
    op.drop_column('task', 'created_by', schema='tasks')
    # ### end Alembic commands ###
