"""tasks table created

Revision ID: 7d8ab5b26f1e
Revises: 
Create Date: 2026-08-29 16:27:14.631319

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8ab5b26f1e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_priority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_priority_id'), 'task_priority', ['id'], unique=False, schema='tasks')
    op.create_index(op.f('ix_tasks_task_priority_title'), 'task_priority', ['title'], unique=True, schema='tasks')
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_status_id'), 'task_status', ['id'], unique=False, schema='tasks')
    op.create_index(op.f('ix_tasks_task_status_title'), 'task_status', ['title'], unique=True, schema='tasks')
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['priority_id'], ['tasks.task_priority.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['tasks.task_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_id'), 'task', ['id'], unique=False, schema='tasks')
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'UPDATE', 'DELETE', name='taskoperation'), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_history_id'), 'task_history', ['id'], unique=False, schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_history_id'), table_name='task_history', schema='tasks')
    op.drop_table('task_history', schema='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='task', schema='tasks')
    op.drop_table('task', schema='tasks')
    op.drop_index(op.f('ix_tasks_task_status_title'), table_name='task_status', schema='tasks')
    op.drop_index(op.f('ix_tasks_task_status_id'), table_name='task_status', schema='tasks')
    op.drop_table('task_status', schema='tasks')
    op.drop_index(op.f('ix_tasks_task_priority_title'), table_name='task_priority', schema='tasks')
    op.drop_index(op.f('ix_tasks_task_priority_id'), table_name='task_priority', schema='tasks')
    op.drop_table('task_priority', schema='tasks')
    # ### end Alembic commands ###
    