"""first version (taskstatus added)

Revision ID: 9c9430b188f5
Revises: 
Create Date: 2026-08-25 16:21:01.071777

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c9430b188f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_status_id'), 'task_status', ['id'], unique=False, schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_status_id'), table_name='task_status', schema='tasks')
    op.drop_table('task_status', schema='tasks')
    # ### end Alembic commands ###
