"""check constraint on dates

Revision ID: a6544b2ec203
Revises: 16eabcc331c9
Create Date: 2026-08-29 20:10:08.402933

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6544b2ec203'
down_revision: Union[str, Sequence[str], None] = '16eabcc331c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_task_due_date_gte_start_date', 'task', 'due_date >= start_date', schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_task_due_date_gte_start_date', 'task', schema='tasks', type_='check')
    # ### end Alembic commands ###
