"""add sort_order to task_priority

Revision ID: c858824e16b1
Revises: f8ad08ba2ee7
Create Date: 2026-09-06 17:03:42.040856

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c858824e16b1'
down_revision: Union[str, Sequence[str], None] = 'f8ad08ba2ee7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_priority', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False), schema='tasks')
    op.alter_column('task_priority', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_priority', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='tasks')
    op.drop_column('task_priority', 'sort_order', schema='tasks')
    # ### end Alembic commands ###
