"""user entity added

Revision ID: d113c1a4cb6f
Revises: c858824e16b1
Create Date: 2026-09-19 16:14:04.962287

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd113c1a4cb6f'
down_revision: Union[str, Sequence[str], None] = 'c858824e16b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_logout', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_user_email'), 'user', ['email'], unique=True, schema='users')
    op.create_index(op.f('ix_users_user_id'), 'user', ['id'], unique=False, schema='users')
    op.create_table('login_pass_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pass_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_login_pass_code_id'), 'login_pass_code', ['id'], unique=False, schema='users')
    op.create_table('task_assignee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('modified_on', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks'
    )
    op.create_index(op.f('ix_tasks_task_assignee_id'), 'task_assignee', ['id'], unique=False, schema='tasks')
    op.create_index('ix_unique_active_task_assignee', 'task_assignee', ['task_id', 'user_id'], unique=True, schema='tasks', postgresql_where=sa.text('is_deleted = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_active_task_assignee', table_name='task_assignee', schema='tasks', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_tasks_task_assignee_id'), table_name='task_assignee', schema='tasks')
    op.drop_table('task_assignee', schema='tasks')
    op.drop_index(op.f('ix_users_login_pass_code_id'), table_name='login_pass_code', schema='users')
    op.drop_table('login_pass_code', schema='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='user', schema='users')
    op.drop_index(op.f('ix_users_user_email'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    # ### end Alembic commands ###
