"""add is_default to task_priority

Revision ID: f8ad08ba2ee7
Revises: a6544b2ec203
Create Date: 2026-09-06 15:57:45.117958

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8ad08ba2ee7'
down_revision: Union[str, Sequence[str], None] = 'a6544b2ec203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_priority', sa.Column('is_default', sa.Boolean(), nullable=True), schema='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_priority', 'is_default', schema='tasks')
    # ### end Alembic commands ###
